# Generated by Django 4.1.1 on 2022-09-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kassir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('surname', models.CharField(max_length=500)),
                ('passport_seria', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
