# Generated by Django 4.1.1 on 2022-09-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kassir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('product_barcode', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('summa', models.BigIntegerField()),
                ('sold', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kassir.kassir')),
            ],
        ),
    ]
