# Generated by Django 4.1.1 on 2022-09-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nakladnoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('postavshik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('ishlab_chiqaruvchi', models.CharField(max_length=200)),
                ('come_price', models.IntegerField()),
                ('ustiga_foiz', models.FloatField()),
                ('sale_price', models.IntegerField()),
                ('pereotsenka', models.BooleanField(default=False)),
                ('spisaniya', models.BooleanField(default=False)),
                ('vozvrat', models.BooleanField(default=False)),
                ('nakladnoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.nakladnoy')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.type')),
            ],
        ),
    ]
